### ISSUE TITLE
Feature 1: User can search for games

### ISSUE THREAD

**Issue by adrienne-yung** [adrienne-yung/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can search for games by genre

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can select an icon to search for a game by genre

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![feature1homepage](https://user-images.githubusercontent.com/90871776/148828424-8f739b42-c7e2-4b16-b4a9-12c85960d394.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create an HTML for your homepage and add search bar
- [ ] Style your web page and add your icons
- [ ] Make each icon clickable. Upon clicking it once, it highlights and clicking it again would unhighlight
- [ ] Make your GizMMO icon clickable and direct users to the homepage 
- [ ] In your JS file, create a function that listens for all of these icons and filters your games according to genre
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
